### ISSUE TITLE
Please don't anonymize decision makers

### ISSUE THREAD

**Issue by blaggacao** [NixOS/moderation#14]
For accountability reasons, please don't anonymise the quorum present leading to a log entry and note the GitHub handles of the decision makers in the log entry.

Otherwise, the risk of abuse of moderation power is only furthered under the veil of anonymity.

Edit: I'd find it suitable to amend the log as far as this quorum can be reconstructed, since reading through the log, the current anonymity of decisions reads like and impresses to me a cardinal mistake in basic accountability.

**Comment by ryantm** [comment]
The moderation team always involves multiple members in significant decisions like the suspension of a long-time contributor. We also review all decisions together. So in most cases, the entire team always stands behind and is accountable for each moderation decision. The moderation team is not anonymous, you can always look up its current members on the home page. The issue with your proposal is that explicitly writing down names next to the decision would put a target onto individual people. Most people who get banned don't tend to react nicely about it, and the fear of potential repercussions against individual moderators is real.

**Comment by blaggacao** [comment]
@ryantm I find your consideration trending to one-sidedness in light of the importance and implications of the request that has been brought to the moderation team.

The ultimate goal is to put checks in place that prevent the moderation team from derailing into a disservice to the whole community.

These fears are well-reasoned based on the privileged context I could have obtained on some decisions, as well as the constitution mechanisms outlined in #10.

Keeping the moderation team accountable through the wider public to the benefit of the whole community is of paramount importance if we think of dynamics ahead a little bit.
