### ISSUE TITLE
Please drop my access from the moderation group

### ISSUE THREAD

**Issue by Mic92** [NixOS/moderation#16]
Since I left the moderation team,
please remove me from the following resources:

- [x] Remove access to Mjolnir
- Discourse
  - [x] Unset Moderator
  - [x] Remove from Moderation Team
- GitHub
  - [x] Remove from [Moderation team](https://github.com/orgs/NixOS/teams/moderation)
  - [x] Update homepage: https://github.com/NixOS/nixos-homepage/pull/1395
- Bitwarden:
   - [x] Drop bitwarden access
   - [x] Rotate admin matrix password

**Comment by Mic92** [comment]
Actually I am not sure if we should have bitwarden for the NixOS wiki infra, but maybe there is a moderation team or something that I don't need to part of?

**Comment by mweinelt** [comment]
Poked zimbatm to remove you from the moderation team collection.

**Comment by zimbatm** [comment]
@Mic92 removed you.

If you have shared passwords in the nixos-wiki team, can you open another issue, that lists all the team members.

**Comment by mweinelt** [comment]
Matrix account password and access token reset.

Thanks for your work on improving this community!
