### ISSUE TITLE
Offboard ryantm

### ISSUE THREAD

**Issue by ryantm** [NixOS/moderation#19]
- Matrix
  - [x] Remove from room "NixOS Moderation Team (Private)", and set powerlevel to 0
  - [x] Remove from Mjolnir room called "Moderators", and set powerlevel to 0 -- removed from room but didn't change power level...
- Discourse
  - [x] Unset Moderator -- done but still need to unset Admin
  - [x] Remove from Moderation Team
- GitHub
  - [x] Remove from [Moderation team](https://github.com/orgs/NixOS/teams/moderation)
  - [x] Update homepage - https://github.com/NixOS/nixos-homepage/pull/1404
- Bitwarden:
   - [x] Drop bitwarden access
   - [x] Rotate admin matrix password   
- [x]  Remove from community@ alias (via Infrastructure team)

**Comment by zimbatm** [comment]
One item missing from the checklist is the github moderator role available in https://github.com/organizations/NixOS/settings/moderators

**Comment by zimbatm** [comment]
Done on my side.

Thanks for your service @ryantm , being a moderator is not an easy task

**Comment by mweinelt** [comment]
> One item missing from the checklist is the github moderator role available in [github.com/organizations/NixOS/settings/moderators](https://github.com/organizations/NixOS/settings/moderators)

404 for me.

**Comment by zimbatm** [comment]
Only the org owner can see this:
![image](https://github.com/NixOS/moderation/assets/3248/118907bd-51ed-4649-8131-41c88db77fd7)

**Comment by mweinelt** [comment]
Documented in 3dcf9d0b47f4eb3497970decb0fa2d025348689f
