### ISSUE TITLE
Access to community@nixos.org

### ISSUE THREAD

**Issue by zimbatm** [NixOS/moderation#2]
Every member of the moderation team should receive the emails sent to the reporting address. Or we setup a ticketing system to triage them.

**Comment by zimbatm** [comment]
This is blocked on either https://github.com/NixOS/foundation/issues/50 or https://github.com/NixOS/foundation/issues/58

**Comment by alyssais** [comment]
We can't just set it up as a forwarding address for all of us?

**Comment by winterqt** [comment]
> We can't just set it up as a forwarding address for all of us?

My understanding is that it's because only Eelco holds the credentials to do so.

**Comment by ryantm** [comment]
There's nothing stopping @grahamc from re-forwarding the email to the rest of the moderation team.

**Comment by mweinelt** [comment]
Except that graham is already the bottleneck on so many fronts.

**Comment by alyssais** [comment]
Sounds like this is unblocked now?

**Comment by zimbatm** [comment]
The next step is to declare the Gandi forwarding email address in Terraform and change the MX addresses as well

**Comment by mweinelt** [comment]
The forwarding address has been in place for a while.
